### ISSUE TITLE
Gateway message error! Exception: 404 Resource Not Found: {"message": "Unknown Member"}

### ISSUE THREAD

**Issue by green-big-frog** [meew0/discordrb#125]
```
[ERROR : gateway @ 2016-05-17 06:02:33.591] Gateway message error!
[ERROR : gateway @ 2016-05-17 06:02:33.591] Exception: 404 Resource Not Found: {"message": "Unknown Member"}
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/api.rb:53:in `raw_request'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/api.rb:76:in `request'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/api.rb:295:in `member'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/cache.rb:88:in `member'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/data.rb:1323:in `member'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/bot.rb:647:in `update_voice_state'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/bot.rb:1147:in `websocket_message'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/websocket.rb:45:in `call'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-23b1cbe385d3/lib/discordrb/websocket.rb:45:in `block (2 levels) in initialize'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:53:in `instance_exec'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:53:in `block in emit'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:48:in `each'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:48:in `emit'
[ERROR : gateway @ 2016-05-17 06:02:33.591] /usr/local/rvm/gems/ruby-2.3.1/gems/websocket-client-simple-0.3.0/lib/websocket-client-simple/client.rb:58:in `block in connect'
```

**Comment by SnazzyPine25** [comment]
What was the member ID that you were trying to find?

**Comment by green-big-frog** [comment]
can't tell, since my bot is on to many servers etc.

**Comment by SnazzyPine25** [comment]
```
begin
    bot.member(id)
rescue
   # if the member wasnt found, do whatever here.
end
```
This triggers rescue when any error occurs.
Although i did have this in a put request I made that enhances this.

**Comment by meew0** [comment]
It's because Discord sends a voice state of a member that miraculously isn't there, so there's not much I can do except rescue the error and drop the update
