### ISSUE TITLE
GUILD_MEMBER_DELETE handling attempts to access inaccessible server

### ISSUE THREAD

**Issue by green-big-frog** [meew0/discordrb#129]
```
[ERROR : gateway @ 2016-05-30 14:00:41.751] Gateway message error!
[ERROR : gateway @ 2016-05-30 14:00:41.751] Exception: #<Discordrb::Errors::NoPermission: The bot doesn't have the required permission to do this!>
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/api.rb:55:in `rescue in raw_request'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/api.rb:53:in `raw_request'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/api.rb:76:in `request'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/api.rb:285:in `server'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/cache.rb:80:in `server'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/bot.rb:751:in `delete_guild_member'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/bot.rb:1189:in `websocket_message'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/websocket.rb:48:in `call'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/bundler/gems/discordrb-e3c4aa739b06/lib/discordrb/websocket.rb:48:in `block (2 levels) in initialize'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:53:in `instance_exec'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:53:in `block in emit'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:48:in `each'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:48:in `emit'
[ERROR : gateway @ 2016-05-30 14:00:41.751] /usr/local/rvm/gems/ruby-2.3.1/gems/websocket-client-simple-0.3.0/lib/websocket-client-simple/client.rb:58:in `block in connect'
```

Would be nice if this could be only one line long.

**Comment by meew0** [comment]
The point is not that these errors in general should be one line, the point is that this particular error is a bug. I'll look at making some kind of dynamic error reporting system that partially suppresses errors that have happened before, but until then it should be enough to fix this particular problem if it happens
