### ISSUE TITLE
#<ArgumentError: time interval must be positive>

### ISSUE THREAD

**Issue by PoVa** [meew0/discordrb#134]
```
[2016-06-02-12:25:42 ERROR] #<ArgumentError: time interval must be positive>
[2016-06-02-12:25:42 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/voice/voice_bot.rb:344:in `sleep'
[2016-06-02-12:25:42 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/voice/voice_bot.rb:344:in `block in play_internal'
[2016-06-02-12:25:42 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/voice/voice_bot.rb:285:in `loop'
[2016-06-02-12:25:42 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/voice/voice_bot.rb:285:in `play_internal'
[2016-06-02-12:25:42 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/voice/voice_bot.rb:167:in `play'
[2016-06-02-12:25:42 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/voice/voice_bot.rb:218:in `play_file'
[2016-06-02-12:25:42 ERROR] /home/pi/sapphire_bot/lib/sapphire_bot/music_bot/server_queue.rb:90:in `block in play_song'
[2016-06-02-12:25:43 ERROR] /home/pi/sapphire_bot/lib/sapphire_bot/music_bot/server_queue.rb:89:in `loop'
[2016-06-02-12:25:43 ERROR] /home/pi/sapphire_bot/lib/sapphire_bot/music_bot/server_queue.rb:89:in `play_song'
[2016-06-02-12:25:43 ERROR] /home/pi/sapphire_bot/lib/sapphire_bot/music_bot/server_queue.rb:54:in `block in start_loop'
[2016-06-02-12:25:43 ERROR] /home/pi/sapphire_bot/lib/sapphire_bot/music_bot/server_queue.rb:48:in `loop'
[2016-06-02-12:25:43 ERROR] /home/pi/sapphire_bot/lib/sapphire_bot/music_bot/server_queue.rb:48:in `start_loop'
[2016-06-02-12:25:43 ERROR] /home/pi/sapphire_bot/lib/sapphire_bot/music_bot/commands/add.rb:34:in `block in <module:Add>'
[2016-06-02-12:25:43 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/commands/parser.rb:85:in `call'
[2016-06-02-12:25:43 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/commands/parser.rb:85:in `call'
[2016-06-02-12:25:43 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/commands/command_bot.rb:167:in `execute_command'
[2016-06-02-12:25:43 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/commands/command_bot.rb:182:in `simple_execute'
[2016-06-02-12:25:43 ERROR] /home/pi/.rvm/gems/ruby-2.2.4/gems/discordrb-2.1.2/lib/discordrb/commands/command_bot.rb:270:in `block in execute_chain'
```

**Comment by SnazzyPine25** [comment]
Yeah i get this alot, it would randomly stop the playback of the voicebot

**Comment by meew0** [comment]
This means it had to wait a long time for the next packet due to encoding or network latency. I'll add a check for this
