### ISSUE TITLE
"ERROR: Failed to build gem native extension." on Raspberry Pi

### ISSUE THREAD

**Issue by DVU-GSP420** [meew0/discordrb#135]
Hello. Sorry to noob it up in here, but I'm not sure what all I need in order to install the gem on my Pi. I'm using the latest OSMC operating system, which is essentially a customized Raspbian (Debian).

I issued the command:
sudo gem install discordrb

and I got this:

```
Building native extensions.  This could take a while...
ERROR:  Error installing discordrb:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 mkrf_conf.rb
Building native extensions.  This could take a while...
/usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /usr/bin/ruby2.1 extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/ruby2.1
        --with-static-libstdc++
        --without-static-libstdc++
        --with-stdc++lib
        --without-stdc++lib
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
        from /usr/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
        from /usr/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
        from /usr/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
        from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
        from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from /usr/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
        from extconf.rb:6:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/unf-0.2.0.beta2/ext/gems/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /var/lib/gems/2.1.0/gems/unf-0.2.0.beta2/ext/gems/extensions/arm-linux/2.1.0/unf_ext-0.0.7.2/gem_make.out
        from /usr/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:38:in `block in build'
        from /usr/lib/ruby/2.1.0/tempfile.rb:324:in `open'
        from /usr/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:17:in `build'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `synchronize'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/installer.rb:677:in `build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/installer.rb:232:in `install'
        from /usr/lib/ruby/2.1.0/rubygems/resolver/specification.rb:78:in `install'
        from /usr/lib/ruby/2.1.0/rubygems/request_set.rb:206:in `block in install_into'
        from /usr/lib/ruby/2.1.0/rubygems/request_set.rb:198:in `each'
        from /usr/lib/ruby/2.1.0/rubygems/request_set.rb:198:in `install_into'
        from /usr/lib/ruby/2.1.0/rubygems/request_set.rb:119:in `install'
        from /usr/lib/ruby/2.1.0/rubygems/dependency_installer.rb:389:in `install'
        from mkrf_conf.rb:15:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/unf-0.2.0.beta2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/arm-linux/2.1.0/unf-0.2.0.beta2/gem_make.out
```

It appears to be complaining that it can't find something that it needs, but I'm not sure what. Any advice?

**Comment by meew0** [comment]
Do you have some form of build tools installed? I've never used a Raspberry Pi myself but there is surely some package like Ubuntu/Debian's `build-essential` available for it.

**Comment by DVU-GSP420** [comment]
```
Building native extensions.  This could take a while...
Successfully installed unf-0.2.0.beta2
Fetching: domain_name-0.5.20160310.gem (100%)
Successfully installed domain_name-0.5.20160310
Fetching: http-cookie-1.0.2.gem (100%)
Successfully installed http-cookie-1.0.2
Fetching: mime-types-2.99.2.gem (100%)
Successfully installed mime-types-2.99.2
Fetching: netrc-0.11.0.gem (100%)
Successfully installed netrc-0.11.0
Fetching: rest-client-2.0.0.rc2.gem (100%)
Successfully installed rest-client-2.0.0.rc2
Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: minitest-5.9.0.gem (100%)
Successfully installed minitest-5.9.0
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: activesupport-5.0.0.rc1.gem (100%)
ERROR:  Error installing discordrb:
        activesupport requires Ruby version >= 2.2.2.
```

Ugh. I don't know if I can upgrade Ruby on this thing. I'll try to figure it out and let you know how it goes. Thanks!

**Comment by PoVa** [comment]
I'm running my bot on Raspberry Pi 2b with latest Raspbian with no problems (except it's slow AF).

**Comment by DVU-GSP420** [comment]
How'd you upgrade your ruby? I'm using apt-get over here and it gave me 2.1.5.

**Comment by meew0** [comment]
If it's only activesupport that's giving you this problem, you can just install a version <5 (try 4.2.6). I don't need any v5 specific functionality.

**Comment by DVU-GSP420** [comment]
I have no idea what activesupport is or how to tell it to do that.

**Comment by PoVa** [comment]
Using rvm: http://installfest.railsbridge.org/installfest/linux

**Comment by DVU-GSP420** [comment]
Looks like its working on 2.1.5. Trying test script...
