### ISSUE TITLE
Exception: #<TypeError: no implicit conversion of Symbol into Integer>

### ISSUE THREAD

**Issue by greenbigfrog** [meew0/discordrb#185]
Today I ran into the following all of a sudden:

```
[ERROR : gateway @ 2016-08-19 15:12:31.500] Gateway message error!
[ERROR : gateway @ 2016-08-19 15:12:31.500] Exception: #<TypeError: no implicit conversion of Symbol into Integer>
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/events/message.rb:156:in `[]'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/events/message.rb:156:in `matches?'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/bot.rb:1529:in `block in raise_event'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/bot.rb:1528:in `each'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/bot.rb:1528:in `raise_event'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/bot.rb:1206:in `websocket_message'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/websocket.rb:48:in `call'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/discordrb-a5e21a59b255/lib/discordrb/websocket.rb:48:in `block (2 levels) in initialize'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:53:in `instance_exec'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:53:in `block in emit'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:48:in `each'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/gems/event_emitter-0.2.5/lib/event_emitter/emitter.rb:48:in `emit'
[ERROR : gateway @ 2016-08-19 15:12:31.500] /usr/local/rvm/gems/ruby-2.3.0/gems/websocket-client-simple-0.3.0/lib/websocket-client-simple/client.rb:58:in `block in connect'

```

**Comment by meew0** [comment]
Actually, this is probably not a bug: you're misusing the event handler method. To me it seems like you're using an array in place of a hash for the attributes but to be sure I'd have to see your code.

**Comment by greenbigfrog** [comment]
You got access to it :)

But I'll check myself tommorow

**Comment by meew0** [comment]
The last update to your code is from 5 days ago, it seems, so I can't view it if it happened today.

**Comment by greenbigfrog** [comment]
No changes since then... Also no updates... Just started randomly.

**Comment by meew0** [comment]
Has this been resolved?

**Comment by greenbigfrog** [comment]
No idea... It just occured randomly... I'll close it for now... (Hasn't been happening for like a week)
