### ISSUE TITLE
"Opus unavailable" message doesn't show up while not in debug mode.

### ISSUE THREAD

**Issue by PoVa** [meew0/discordrb#216]
```
[2016-09-10-18:13:53 ERROR] Gateway message error!
[2016-09-10-18:13:53 ERROR] An error occurred in the main websocket loop!
[2016-09-10-18:13:53 ERROR] An error occurred while connecting to the websocket!
```

In debug mode:

```
[2016-09-10-18:10:10 ERROR] Gateway message error!
[2016-09-10-18:10:10 ERROR] #<LoadError: Opus unavailable - voice not supported! Please install opus for voice support to work.>
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/voice/encoder.rb:35:in `initialize'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/voice/voice_bot.rb:96:in `new'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/voice/voice_bot.rb:96:in `initialize'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/bot.rb:594:in `new'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/bot.rb:594:in `update_voice_server'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/bot.rb:890:in `handle_dispatch'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/bot.rb:508:in `dispatch'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:593:in `handle_dispatch'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:560:in `handle_message'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:510:in `websocket_loop'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:468:in `connect'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:374:in `block in connect_loop'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:372:in `loop'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:372:in `connect_loop'
[2016-09-10-18:10:10 ERROR] /home/Kristupas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/discordrb-3ebc818df117/lib/discordrb/gateway.rb:145:in `block in run_async'
```

**Comment by meew0** [comment]
Actually, are you sure there is a difference? All of these messages are errors, and debug mode has no effect on errors being printed.

**Comment by PoVa** [comment]
You're right, this was on my side...
