### ISSUE TITLE
creating DM channels responds with 400

### ISSUE THREAD

**Issue by greenbigfrog** [meew0/discordrb#227]
On latest master:
```
[5] pry(main)> Discordrb::API::User.create_private(bot.token, 170220684675383297)
RestClient::BadRequest: 400 Bad Request
from /home/frog/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:223:in `exception_with_response'
[6] pry(main)> bot.user(170220684675383297).pm
=> <Channel name=Talha2506 id=183566388122615809 topic="" type=text position= server=>
```

On gateway-v6 PR:
```
[12] pry(main)> bot.user(170220684675383297).pm
=> <Channel name=Talha2506 id=183566388122615809 topic="" type=1 position= server=>
[13] pry(main)> Discordrb::API::User.create_pm(bot.token, 170220684675383297)
RestClient::BadRequest: 400 Bad Request
from /home/frog/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:223:in `exception_with_response'
```

Doing a postman request works perfectly. (I've been encountering this randomly accross users (but only starting a month ago or so), users that have been using my bot for "years" and users that just found my bot)

**Comment by heimidal** [comment]
Can confirm on my end. The following code causes some users to not receive a PM and results in a 400 Bad Request error in the logs:

```ruby
module Events
    extend Discordrb::Commands::CommandContainer

    command :'new-event', description: 'Create a new event.' do |event|
        event.author.pm "Create your event by going to the following link. Don't share this link with others -- tell them to ask the bot for their own link! #{ENV['SAAG_SERVER_ADDRESS']}/events/new?author_id=#{event.author.id}"
    end
end
```

This is not limited to new users to the server, though anecdotally those users appear to be affected more often.

**Comment by heimidal** [comment]
I should add: restarting the server clears up the issues for some users, so this feels like a cache looking issue or something.

**Comment by heimidal** [comment]
I believe I've fixed this in https://github.com/meew0/discordrb/pull/228
