### ISSUE TITLE
break if throws errors when breaking out of some message events

### ISSUE THREAD

**Issue by benetherington** [meew0/discordrb#264]
When running the example code from the wiki...

```
rate_limiter = Discordrb::Commands::SimpleRateLimiter.new
rate_limiter.bucket :example, delay: 5  # 5 seconds between each execution
bot.message(containing: ['(╯°□°）╯︵ ┻━┻', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', '(ノಠ益ಠ)ノ彡┻━┻']) do |event|
  break if rate_limiter.rate_limited?(:example, event.channel)
  event.respond '┬─┬ノ( º _ ºノ)'
end
```

The following error is thrown if you exceed the 5 second delay.

```
[ERROR : et-2 @ 2016-11-06 12:52:45.336] Exception: #<LocalJumpError: break from proc-closure>
[ERROR : et-2 @ 2016-11-06 12:52:45.336] #{your code location}:in `block in <main>'
[ERROR : et-2 @ 2016-11-06 12:52:45.336] /Users/admin/.rvm/gems/ruby-2.2.3/gems/discordrb-3.1.1/lib/discordrb/events/generic.rb:82:in `call'
[ERROR : et-2 @ 2016-11-06 12:52:45.336] /Users/admin/.rvm/gems/ruby-2.2.3/gems/discordrb-3.1.1/lib/discordrb/events/generic.rb:82:in `call'
[ERROR : et-2 @ 2016-11-06 12:52:45.336] /Users/admin/.rvm/gems/ruby-2.2.3/gems/discordrb-3.1.1/lib/discordrb/bot.rb:1140:in `block in call_event'
```

Note that enclosing the `event.respond` in an `if` statement (instead of preceding with a `break if`), no error is thrown.

**Comment by meew0** [comment]
Ah, you're supposed to use `next` to stop events early. I'll change this in the wiki.
