### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Punknoodles** [meew0/discordrb#287]
executing `gem install discordrb --platform=ruby` returns: 
```
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing discordrb:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext
C:/Ruby23/bin/ruby.exe -r ./siteconf20161210-7048-row8ik.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby23/bin/$(RUBY_BASE_NAME)
        --with-static-libstdc++
        --without-static-libstdc++
        --with-stdc++lib
        --without-stdc++lib
C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/unf_ext-0.0.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.2 for inspection.
Results logged to C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/unf_ext-0.0.7.2/gem_make.out
```

executing `ruby -v` returns:
`ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]`

executing `gem -v` returns:
`2.6.8`

can anyone help me?

**Comment by z64** [comment]
`C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.`

Please read the dependencies section of the README.

https://github.com/meew0/discordrb#dependencies

**Comment by Punknoodles** [comment]
I already downloaded DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe and run, unpacked to C:\DevKit, and `cd C:\DevKit`. Then `ruby dk.rb init` returned:
```
[INFO] found RubyInstaller v2.3.1 at C:/Ruby23

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.
```
And after `ruby dk.rb install` gave me:
```
[INFO] Skipping existing gem override for 'C:/Ruby23'
[WARN] Skipping existing DevKit helper library for 'C:/Ruby23'
```
I think something went wrong at `ruby dk.rb install`.

**Comment by Punknoodles** [comment]
mkmf.txt contains:
```
"gcc -o conftest.exe -IC:/Ruby23/include/ruby-2.3.0/i386-mingw32 -IC:/Ruby23/include/ruby-2.3.0/ruby/backward -IC:/Ruby23/include/ruby-2.3.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Ruby23/lib -L.      -lmsvcrt-ruby230  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Ruby23/include/ruby-2.3.0/ruby.h:33:0,
                 from conftest.c:1:
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:131:14: error: size of array 'ruby_check_sizeof_voidp' is negative
In file included from C:/Ruby23/include/ruby-2.3.0/ruby.h:33:0,
                 from conftest.c:1:
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_obj_freeze_inline':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1360:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1361:2: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1362:6: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1362:27: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_data_object_get':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1400:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_data_object_make':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1414:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_data_typed_object_make':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1421:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_num2char_inline':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1587:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1587:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1587:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1587:41: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1587:41: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1587:41: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1588:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1588:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1588:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_class_of':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1949:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_type':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1966:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
In file included from C:/Ruby23/include/ruby-2.3.0/ruby.h:33:0,
                 from conftest.c:1:
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_clone_setup':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1997:56: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1998:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1999:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:1999:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_dup_setup':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2005:42: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2006:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2006:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_array_len':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2012:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2013:2: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2013:24: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_array_const_ptr':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2027:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2027:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2027:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_struct_len':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2034:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2035:2: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2035:26: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h: In function 'rb_struct_const_ptr':
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2041:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2041:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
C:/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2041:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

```

**Comment by z64** [comment]
It would seem so. Had you previously installed an incorrect version of the DevKit, like the 64bit one? In any case, removing the DevKit before attempting to update / reinstall as you did should fix this:

https://github.com/oneclick/rubyinstaller/wiki/FAQ#devkit-self-extracting-executable-sfx

**Comment by meew0** [comment]
Closing this for now due to inactivity, it's better to ask such questions in the [dedicated Discord channel](https://discord.gg/0SBTUU1wZTWfFQL2).

**Comment by Daniel-Worrall** [comment]
I came across this myself lately on an environment I don't usually use. The problem was having the Devkit mismatched with Ruby. (32/64bit)

Posting for future reference for anyone finding later.
