### ISSUE TITLE
VoiceStateUpdateEventHandler fails when a user leaves a channel with channel parameters

### ISSUE THREAD

**Issue by Daniel-Worrall** [meew0/discordrb#301]
Ignoring the bad title, minimal reproduction code is
```
bot.voice_state_update(channel: '') {}
bot.voice_state_update(channel: 1) {}
```
A VoiceStateUpdate will not send a channel when a user disconnects and so the matching fails when checking a channel (for both String and Integer)

Possible solutions would be to use Ruby 2.3 safe method checking, or wait for the EventHandler rewrite.

```
[ERROR : websocket @ 2017-01-10 13:21:17.408] Exception: #<NoMethodError: undefined method `name' for nil:NilClass>
[ERROR : websocket @ 2017-01-10 13:21:17.408] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/events/voice
_state_update.rb:75:in `block in matches?'
[ERROR : websocket @ 2017-01-10 13:21:17.408] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/events/gener
ic.rb:46:in `matches_all'
[ERROR : websocket @ 2017-01-10 13:21:17.408] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/events/gener
ic.rb:90:in `matches_all'
[ERROR : websocket @ 2017-01-10 13:21:17.409] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/events/voice
_state_update.rb:73:in `matches?'
[ERROR : websocket @ 2017-01-10 13:21:17.409] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/bot.rb:1159:
in `block in raise_event'
[ERROR : websocket @ 2017-01-10 13:21:17.409] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/bot.rb:1158:
in `each'
[ERROR : websocket @ 2017-01-10 13:21:17.412] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/bot.rb:1158:
in `raise_event'
[ERROR : websocket @ 2017-01-10 13:21:17.412] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/bot.rb:1023:
in `handle_dispatch'
[ERROR : websocket @ 2017-01-10 13:21:17.413] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/bot.rb:582:i
n `dispatch'
[ERROR : websocket @ 2017-01-10 13:21:17.413] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:5
98:in `handle_dispatch'
[ERROR : websocket @ 2017-01-10 13:21:17.413] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:5
65:in `handle_message'
[ERROR : websocket @ 2017-01-10 13:21:17.413] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:5
15:in `websocket_loop'
[ERROR : websocket @ 2017-01-10 13:21:17.413] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:4
73:in `connect'
[ERROR : websocket @ 2017-01-10 13:21:17.413] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:3
79:in `block in connect_loop'
[ERROR : websocket @ 2017-01-10 13:21:17.414] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:3
78:in `loop'
[ERROR : websocket @ 2017-01-10 13:21:17.414] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:3
78:in `connect_loop'
[ERROR : websocket @ 2017-01-10 13:21:17.414] C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/discordrb-ca92f56fc84c/lib/discordrb/gateway.rb:1
45:in `block in run_async'
```

**Comment by meew0** [comment]
I don't want to make anything dependent on the event handler rewrite because it's not really convoluted in the same way that CommandBot is – you can mostly pile more stuff onto handlers without making the (bad) structure much worse.

Regardless of that this is a caching problem; ideally the event for voice state updates should look into the cache and get the old channel ID. This shouldn't be much of a problem as I'm pretty sure voice states are fairly robust right now.

**Comment by meew0** [comment]
For future reference, I solved this not as I said by getting the old channel ID, but rather just using a nil check. Instead I added a separate `old_channel`/`:old_channel` attribute to check for that.
