### ISSUE TITLE
An error may occur at sending UDP packet

### ISSUE THREAD

**Issue by purintai** [meew0/discordrb#38]
Sometimes occurs error as described below, should be ignore this error?

```
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] Exception: #<Errno::EPERM: Operation not permitted - sendto(2) for "128.199.192.225" port 50172>
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/network.rb:49:in `send'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/network.rb:49:in `send_packet'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/network.rb:35:in `send_audio'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/voice_bot.rb:133:in `block in play_internal'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/voice_bot.rb:98:in `loop'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/voice_bot.rb:98:in `play_internal'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/voice_bot.rb:73:in `play'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] /usr/local/rvm/gems/ruby-2.3.0/gems/discordrb-1.5.3/lib/discordrb/voice/voice_bot.rb:77:in `play_file'
[DEBUG : et-15 @ 2016-01-12 04:04:40 +0000] discordvoice.rb:37:in `block in <main>'
```

```ruby
# monkey patch
class Discordrb::Voice::VoiceUDP
    private
    def send_packet(packet)
        begin
            @socket.send(packet, 0, @endpoint, @port)
        rescue Errno::EPERM
            puts "debug: error on sending udp packet"
        end
    end
end
```

**Comment by purintai** [comment]
I found similar [issue](https://github.com/Graylog2/gelf-rb/issues/29) and [patch](https://github.com/swalberg/gelf-rb/commit/14d7238d8ff164c20b29639b07bbfc11dce3f10c) for it.

and I made monkey patch and try it, but error occurs as ever.

```ruby
# monkey patch v2
class Discordrb::Voice::VoiceUDP
    def send_audio(buf, sequence, time)
      packet = [0x80, 0x78, sequence, time, @ssrc].pack('CCnNN') + buf
      send_packet2(packet)
    end

    private
    
    def send_packet2(packet)
        begin
            socket = Thread.current[:gelf_socket] ||= UDPSocket.new
            socket.send(packet, 0, @endpoint, @port)
        rescue Errno::EPERM
            puts "debug: error on sending udp packet"
        end
    end
end
```

**Comment by meew0** [comment]
Does the playback still work?

**Comment by purintai** [comment]
Yes.

**Comment by meew0** [comment]
I'm not sure what causes this problem, it might be a permissions problem on your system, but if it doesn't prevent playback you can probably ignore it.

**Comment by meew0** [comment]
As discussed on Discord, this is likely a problem with c9's configuration so I'm closing this.

**Comment by Cyan101** [comment]
can this at least be added to the wiki for fellow c9 users?

**Comment by meew0** [comment]
Done, see [here](https://github.com/meew0/discordrb/wiki/Voice-sending#troubleshooting)

**Comment by Cyan101** [comment]
Was talking with @VxJasonxV and using RVM 2.3.3 on C9 rather than rbenv or apt or the version cloud9 has installed by default seems to fix any issues
