### ISSUE TITLE
Selfbot fails to join server with a NoPermission error

### ISSUE THREAD

**Issue by astronautlevel2** [meew0/discordrb#396]
Upon attempting to call the .join() method on a selfbot, I get a NoPermission error.

Here is the code
```rb
bot = Discordrb::Bot.new(token: token, type: :user)
bot.run(true)
bot.join(invite)
```

And here is the stacktrace:

```
alex@sayaka  ~  ruby selfbot.rb
Using WSCS version: 0.3.0
[INFO : websocket @ 2017-08-12 22:03:55.593] Discord using gateway protocol version: 6, requested: 6
/home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/api.rb:68:in `rescue in raw_request': The bot doesn't have the required permission to do this! (Discordrb::Errors::NoPermission)
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/api.rb:66:in `raw_request'
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/api.rb:92:in `request'
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/api/user.rb:8:in `resolve'
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/cache.rb:67:in `user'
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/data.rb:1005:in `initialize'
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/cache.rb:191:in `new'
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/cache.rb:191:in `invite'
	from /home/alex/.gem/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/bot.rb:259:in `join'
	from selfbot.rb:7:in `<main>'

```

I'm aware that it's impossible to use join as a bot, but this bot is running on a user account, so it should work.

**Comment by z64** [comment]
Hi there!

This request fails because the bot attempts to resolve the `inviter` portion of the invite object from `GET /invites/{code}`

```json
{
  "inviter": {
    "username": "Cyan",
    "discriminator": "0340",
    "id": "141793632171720704",
    "avatar": "c6fef8a33f2f1e8f0313926b1ea6aa35"
  },
  "code": "***",
  "guild": {
    "splash": null,
    "id": "321941583152807948",
    "icon": "99da3f8f4abcf93b50d7766c0f6ca4f7",
    "name": "Emoji"
  },
  "channel": {
    "type": 0,
    "id": "321941583152807948",
    "name": "emoji"
  }
}
```

User tokens do not have access to `GET /users/{user.id}` to resolve the inviter that hasn't been cached yet, as `Invite.new` (when trying to resolve the invite through `Cache#invite`) tries to call here:
```rb
class Invite
  def initialize(data)
    # ..
    @inviter = data['inviter'] ? (@bot.user(data['inviter']['id'].to_i) || User.new(data['inviter'], bot)) : nil
    # ..
  end
end
```
https://github.com/meew0/discordrb/blob/master/lib/discordrb/data.rb#L1111

But moreover, the practice of accepting invites with a user token is not a supported use case of the API and could result in consequences like your account becoming unverified. As such, this is `wontfix`.

**Comment by astronautlevel2** [comment]
Hey, thank you for your prompt reply

If the practice of accepting invites with a user token is not supported, and bot accounts can't accept invites, what is the intended purpose of join?

Thanks

**Comment by z64** [comment]
It is possible to use invites with an OAuth2 Bearer token.
