### ISSUE TITLE
`Bot#run` not reconnecting (properly) upon connection loss

### ISSUE THREAD

**Issue by Lavode** [meew0/discordrb#406]
I have had a few cases where - upon seemingly losing connection - the bot did not reconnect on its own. 
Within Disord, the bot is unresponsive, and shows as offline (grey lightbulb).

Last few lines of the log - showing it noticing that the connection is dead, but not reconnecting:
```
[ERROR : websocket @ 2017-09-08 18:04:37.284] The websocket connection has closed: nil
[ERROR : websocket @ 2017-09-08 18:04:37.284] Websocket close frame received!
[ERROR : websocket @ 2017-09-08 18:04:37.284] Code: 1001
[ERROR : websocket @ 2017-09-08 18:04:37.284] Message: CloudFlare WebSocket proxy restarting
[ERROR : heartbeat @ 2017-09-08 18:04:38.626] An error occurred while heartbeating!
[ERROR : heartbeat @ 2017-09-08 18:04:38.626] Exception: #<RuntimeError: Tried to send something to the websocket while not being connected!>
[ERROR : heartbeat @ 2017-09-08 18:04:38.626] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:743:in `send'
[ERROR : heartbeat @ 2017-09-08 18:04:38.626] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:735:in `send_packet'
[ERROR : heartbeat @ 2017-09-08 18:04:38.626] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:257:in `send_heartbeat'
[ERROR : heartbeat @ 2017-09-08 18:04:38.627] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:250:in `heartbeat'
[ERROR : heartbeat @ 2017-09-08 18:04:38.627] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:414:in `block (2 levels) in setup_heartbeats'
[ERROR : heartbeat @ 2017-09-08 18:04:38.627] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:407:in `loop'
[ERROR : heartbeat @ 2017-09-08 18:04:38.627] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:407:in `block in setup_heartbeats'
[INFO : websocket @ 2017-09-08 18:06:41.182] Discord using gateway protocol version: 6, requested: 6
[ERROR : websocket @ 2017-09-08 18:42:00.079] The websocket connection has closed: nil
[ERROR : websocket @ 2017-09-08 18:42:00.079] Websocket close frame received!
[ERROR : websocket @ 2017-09-08 18:42:00.079] Code: 1000
[ERROR : websocket @ 2017-09-08 18:42:00.079] Message: 
[WARN : heartbeat @ 2017-09-08 18:42:26.681] Last heartbeat was not acked, so this is a zombie connection! Reconnecting


^C
root@application:~# date
Fri Sep  8 21:29:44 UTC 2017
```

The pplication is running within a Docker container, on a Debian 8 host.
Discordrb version `3.2.0` is used.

I will be running the bot with a higher logging verbosity, in hopes of capturing something useful. Mind that these occurences are very rare though (~once a month), so I might not be able to provide further details right away.

**Comment by z64** [comment]
Hey there @Lavode , you mentioned you'd be doing further investigation on this with a higher logging level - did you have anything more to add to this issue / has it occurred since?

**Comment by Lavode** [comment]
@z64 Hey, so far it has - sadly - not happened again. I'll update the issue if it does happen again, though.

**Comment by z64** [comment]
Gonna close this for now @Lavode - if you have any more details, please feel free to comment back / reopen. You can join us [on the Discord API server](https://discord.gg/0SBTUU1wZTWfFQL2) too.
