### ISSUE TITLE
Exception raised when connecting to voice channel, can't send voice or do anything else

### ISSUE THREAD

**Issue by da-moo** [meew0/discordrb#450]
Gemfile:
```ruby
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git', branch: 'master'
```

Code:
```ruby
@voice_bot = bot.voice_connect(bot.find_channel('<channel name>', '<server name>')[0])
```

Exception/stacktrace:
```
#<Thread:0x00007fc03c32d1c0@/home/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/discordrb-31163396a95c/lib/discordrb/voice/network.rb:252 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /home/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/discordrb-31163396a95c/lib/discordrb/voice/network.rb:254:in `block in connect'
        2: from /home/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/discordrb-31163396a95c/lib/discordrb/voice/network.rb:302:in `init_ws'
        1: from /home/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/discordrb-31163396a95c/lib/discordrb/voice/network.rb:302:in `new'
/home/azureuser/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/discordrb-31163396a95c/lib/discordrb/websocket.rb:32:in `initialize': uninitialized constant Discordrb::WebSocket::Client (NameError)
```
I'm running that code using an eval command on my own personal test server. The exception occurs as soon as the bot is visible in the voice channel.

**Comment by z64** [comment]
Thanks for reporting! Sorry about that. Fixed in the above commit.
