### ISSUE TITLE
Websocket connection reset by peer when running from Docker container

### ISSUE THREAD

**Issue by egee-irl** [meew0/discordrb#451]
I've been noticing the follow errors after having my bot run in a container all night:

```
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:53.999] An error occurred in the main websocket loop!
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] Exception: #<Errno::ECONNRESET: Connection reset by peer>
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:57:in `sysread'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:57:in `fill_rbuff'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:98:in `read'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:262:in `getc'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:544:in `block in websocket_loop'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:544:in `synchronize'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:544:in `websocket_loop'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:525:in `connect'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:432:in `block in connect_loop'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:431:in `loop'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:431:in `connect_loop'
androgee_1  | [ERROR : websocket @ 2018-01-25 11:14:54.000] /usr/local/bundle/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:161:in `block in run_async'
androgee_1  | [WARN : heartbeat @ 2018-01-25 11:15:35.246] Last heartbeat was not acked, so this is a zombie connection! Reconnecting
androgee_1  | [ERROR : heartbeat @ 2018-01-25 11:15:35.246] The websocket connection has closed: nil
androgee_1  | [INFO : websocket @ 2018-01-25 11:15:36.006] Instant reconnection flag was set - reconnecting right away
```
This connection error does not happen when I run the bot locally, outside of my Docker container. The container is running ```ruby:2.4``` and there's other websocket stuff happening on the bot, so maybe something is conflicting?

I'm not really sure where to start in debugging this. I've considered just having the bot re-establish connection if it is dropped, but I've never seen the connection drop before so clearly something is wrong.

**Comment by egee-irl** [comment]
The repo & code for the bot can be found here - https://github.com/egee-irl/androgee-ruby

**Comment by z64** [comment]
Closing this for now as there isn't anything actionable here. If you have other questions or find any additional information that you think we can help with, please feel free to reopen or [join us on Discord](https://discord.gg/cyK3Hjm). Thanks!
