### ISSUE TITLE
Possible bug in monkey patching Discordrb::MessageEvent

### ISSUE THREAD

**Issue by PenguinOwl** [meew0/discordrb#466]
Log:
```
/app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:503:in `const_get': uninitialized constant Discordrb::MessageEventHandler (NameError)
Did you mean?  Discordrb::MessageEvent

from /app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:503:in `block in class_from_string'
from /app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:502:in `each'
from /app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:502:in `inject'
from /app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:502:in `class_from_string'
from /app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:484:in `handler_class'
from /app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:512:in `register_event'
from /app/vendor/bundle/ruby/2.3.0/gems/discordrb-3.2.1/lib/discordrb/container.rb:37:in `message'
```

Code to reproduce:
```ruby
class Discordrb::MessageEvent
  attr_accessor :conn
end
```

Not sure if this is intentional or a bug.

**Comment by z64** [comment]
I'm not sure what you're doing, but that is not a class used by `discordrb`. 

It's `Discordrb::Events::MessageEvent`, not `Discordrb::MessageEvent`.

I also can't reproduce this simply off of:

```rb
require 'discordrb'

class Discordrb::MessageEvent
  attr_accessor :foo
end
```

If you think this is still an issue, please provide a more complete example.

**Comment by PenguinOwl** [comment]
Whoops, looks like I spaghettied myself. Thanks for the correction!
