### ISSUE TITLE
Error: Could not create makefile

### ISSUE THREAD

**Issue by bybb** [meew0/discordrb#52]
I have no idea why it is doing this...

Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing discordrb:
        ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160215-10416-15k84nj.rb extconf.rb
checking for main() in -lssleay32... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-ssleay32lib
        --without-ssleay32lib
C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `each'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/eventmachine-1.0.9.1/gem_make.out

**Comment by meew0** [comment]
Are you sure your devkit is the same architecture as your Ruby installation (32/64 bit)? Try reinstalling them both as 32 bit, I've found it to be the safest solution.

**Comment by bybb** [comment]
Ok I'll try that

**Comment by meew0** [comment]
Did it work?

**Comment by meew0** [comment]
Closing due to inactivity. If it's still a problem, I'll reopen it
