### ISSUE TITLE
VoiceBot does not disconnect from channel when destroy is called.

### ISSUE THREAD

**Issue by torce** [meew0/discordrb#58]
I was trying to make a simple music-playing bot. The bot can play files correctly, but when `bot.voice.destroy` is called, the bot does not disconnect from the channel and the subsequent calls to `bot.voice.play` doesn't work.

Here is a code snippet that reproduces the problem with the command sequence `!play file`, `!destroy` and `!play file`:
```ruby
require 'discordrb'

bot = Discordrb::Commands::CommandBot.new 'user@example.com', 'password', '!'

bot.command :play do |event, path|
  channel_name = event.bot.find('/pol/')
  event.bot.voice_connect(channel_name.first)
  event.bot.voice.encoder.use_avconv = true
  file_path = File.expand_path("../files/#{path.gsub('../', '')}.mp3", __FILE__)
  puts "Playing #{file_path}"
  event.bot.voice.play_file file_path
end

bot.command :destroy do |event|
  event.bot.voice.destroy
end

bot.run
```
Regards.

**Comment by meew0** [comment]
Does calling `destroy` twice do anything?

**Comment by torce** [comment]
Calling it twice seem to have no effect. However, if after calling it twice you try to play again the mp3 file it sometimes cause a segmentation fault.

I don't understand yet what conditions causes the segfault so I will continue testing and post here if I find something.
```
/home/david/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:202: [BUG] Segmentation fault at 0x00000000000000
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0026 e:000025 CFUNC  :release_machine
c:0007 p:0034 s:0023 e:000022 RESCUE /home/david/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:202
c:0006 p:0405 s:0020 e:000019 METHOD /home/david/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:226
c:0005 p:0051 s:0013 E:0025d8 METHOD /home/david/.rvm/gems/ruby-2.2.1/gems/discordrb-1.7.1/lib/discordrb/bot.rb:742
c:0004 p:0007 s:0009 e:000008 BLOCK  /home/david/.rvm/gems/ruby-2.2.1/gems/discordrb-1.7.1/lib/discordrb/bot.rb:141 [FINISH]
c:0003 p:---- s:0007 e:000006 CFUNC  :loop
c:0002 p:0032 s:0004 e:000003 BLOCK  /home/david/.rvm/gems/ruby-2.2.1/gems/discordrb-1.7.1/lib/discordrb/bot.rb:140 [FINISH]
c:0001 p:---- s:0002 e:000001 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/david/.rvm/gems/ruby-2.2.1/gems/discordrb-1.7.1/lib/discordrb/bot.rb:140:in `block in run_async'
/home/david/.rvm/gems/ruby-2.2.1/gems/discordrb-1.7.1/lib/discordrb/bot.rb:140:in `loop'
/home/david/.rvm/gems/ruby-2.2.1/gems/discordrb-1.7.1/lib/discordrb/bot.rb:141:in `block (2 levels) in run_async'
/home/david/.rvm/gems/ruby-2.2.1/gems/discordrb-1.7.1/lib/discordrb/bot.rb:742:in `websocket_connect'
/home/david/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:226:in `run'
/home/david/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:202:in `ensure in run'
/home/david/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:202:in `release_machine'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f9a97d33b45 RBP: 0x00007f9a841d2030 RSP: 0x00007f9a92a147e0
 RAX: 0x00007f9a841d2030 RBX: 0x00007f9a84000078 RCX: 0x00007f9a84000078
 RDX: 0x0000000000000211 RDI: 0x00007f9a841cb920 RSI: 0x00007f9a841d3b90
  R8: 0x00007f9a84000038  R9: 0x00007f9a84000070 R10: 0x00007f9a92a14520
 R11: 0x00007f9a96358e10 R12: 0x0000ff35081d20a8 R13: 0x0000000000000620
 R14: 0x00007f9a840b7f10 R15: 0x00007f9a84000020 EFL: 0x0000000000010206

```

**Comment by meew0** [comment]
Yeah, I've also gotten a segfault. I'll investigate this
