### ISSUE TITLE
Release new version with updated rbnacl?

### ISSUE THREAD

**Issue by localhostdotdev** [meew0/discordrb#621]
Was bumped in 4b47a27c3148d4f99a88e747f77ac823801c72b1

I'm not sure yet but seems to be causing errors when libsodium is not present instead of ignoring it.

**Comment by z64** [comment]
Could you please share the errors you're referring to?

**Comment by localhostdotdev** [comment]
On Heroku:

```
2019-04-04T17:58:59.786870+00:00 app[web.1]: libsodium not available! You can continue to use discordrb as normal but voice support won't work.
2019-04-04T17:58:59.786921+00:00 app[web.1]: Read https://github.com/meew0/discordrb/wiki/Installing-libsodium for more details.
2019-04-04T17:59:00.341185+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:7: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION
2019-04-04T17:59:00.341227+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:7: warning: previous definition of MINIMUM_LIBSODIUM_VERSION was here
2019-04-04T17:59:00.342554+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/ffi-1.10.0/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'sodium': sodium: cannot open shared object file: No such file or directory. (LoadError)
2019-04-04T17:59:00.342560+00:00 app[web.1]: Could not open library 'libsodium.so': libsodium.so: cannot open shared object file: No such file or directory
2019-04-04T17:59:00.342562+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.6.0/gems/ffi-1.10.0/lib/ffi/library.rb:99:in `map'
```

(fixed with a custom heroku buildpack that installs libsodium)

**Comment by z64** [comment]
> (fixed with a custom heroku buildpack that installs libsodium and using discordrb from discord)

Could you clarify what you mean by this?

In any case, this has been reported before (on 3.3, before the change you mentioned) and it is generally understood to be an OS packaging issue with libsodium, outside of the scope of the library.

**Comment by localhostdotdev** [comment]
I had the last released version of the discordrb gem and a regular heroku dyno with ruby and active storage buildpacks.

When I pushed to Heroku, dyno crashed.

I used an heroku buildpack to have libsodium available: https://github.com/localhostdotdev/heroku-buildpack-libsodium

Meanwhile I also upgraded discordrb to use the last version from github.

So not sure which of those two steps (or maybe the two of them) fixed the issue.

Anyway, issue is fixed for me, having a released gem that is using the latest rbnacl **might** prevent other users from running into this issue.

**Comment by z64** [comment]
This issue was reported once about a year ago (3.2.1), and recently a month ago (3.3) - so I'm more than confident it is a host issue with vendoring libsodium. Your fork of the buildpack suggests this as well. You could probably downgrade drb now to isolate the change to verify if you wanted.

**Comment by Exelord** [comment]
It'd still valid issue. Sodium seems required to run this gem

**Comment by z64** [comment]
This LoadError does not come from discordrb. See: https://github.com/meew0/discordrb/blob/master/lib/discordrb/voice/network.rb#L10-L21

If *we* can't load the gem, the exception is caught and we print our warning message. Something else happens when loading the runtime in an environment where libsodium is improperly available. 

You can try running `[bundle exec] ruby -e 'require "libsodium"` to possibly get more details.

People who have encountered this have fixed it by otherwise repairing their libsodium installation. There's nothing discordrb can do here. (Most people who use this gem do not have libsodium installed)

**Comment by Exelord** [comment]
Maybe its related to Rails version? It looks like now Rails are requiring rbnacl during boot, so its way gem your code.

**Comment by z64** [comment]
Even if it is an issue with Rails.. it's an issue with Rails. We couldn't do anything about it because we don't depend on Rails for anything.

I recommend you read the referenced chat log from the last person to encounter this issue (who also happened to be using rails)

https://discordapp.com/channels/81384788765712384/381891448884428801/553370562316075018

<details><summary>Chat Log Excerpt</summary>
<p>

```
[7:17 PM] OmnipotentEntity: It's working now
[7:17 PM] OmnipotentEntity: Here's what I did:
[7:18 PM] OmnipotentEntity: I completely cleared tmp/cache, uninstalled and reinstalled all gems, and stopped spring
[7:19 PM] connor ceo of ruby on rails: why were you using spring with a discord bot?
[7:19 PM] connor ceo of ruby on rails: I've only ever used it with rails apps, I didn't even realize you could use it with anything else
[7:19 PM] OmnipotentEntity: This is a web application that messes with discord stuff
[7:19 PM] connor ceo of ruby on rails: ahhh
[7:20 PM] connor ceo of ruby on rails: makes sense
[7:25 PM] z64: oh huh. so are you just requiring everything normally now? or did you still comment out the require for voice/ @OmnipotentEntity
[7:25 PM] OmnipotentEntity: nope, file is untouched
[7:25 PM] z64: hm. well. alright then. lmao
[7:25 PM] OmnipotentEntity: so it's definitely some sort of environment issue on my end, and not a discordrb bug.
[7:26 PM] OmnipotentEntity: probably stale cache files from when I didn't quite get versions of ruby right.
```

</p>
</details>

**Comment by z64** [comment]
`spring` to me, on the tin, sounds like the most likely culprit. Perhaps it loads all of your dependencies (and nested dependencies), and thereby "skips" our "safe" optional require mechanism. But I'm unaware of its implementation details.

**Comment by z64** [comment]
Be sure to pay close attention to the backtrace as well. Looking at the sample one I posted above, the error stemmed from a nested loading from `bootsnap` that follows gems `oauth` -> `jwt` (which uses encryption) -> `rbnacl` - completely out of tree of discordrb.

![image](https://user-images.githubusercontent.com/6119032/58045279-f9f7c000-7b0f-11e9-8730-dd00e9d5c954.png)
