### ISSUE TITLE
Errors coming out of the blue when just idling

### ISSUE THREAD

**Issue by avengerx** [meew0/discordrb#70]
I have two "bots". (one real unattended bot and other which is just a script running on my account to keep my 'playing' status).

The unattended bot stays just on two low-to-no traffic servers. And I, well, on the API server with lots of activity on channels.

On my client I am running a script with no listeners at all. It is 87 lines long so I think I'd post it if you want it to analyse. But basically the script runs the bot in async and loops on a `STDIN.gets` watching keypresses for console commands. The only command it haves is 'c', for reading the string and then putting it on the `bot.game` variable/property.

Here's a single log (filtered it by the time it happened):
```
[ERROR : websocket @ 2016-03-24 03:12:58.411] Exception: #<Discordrb::Errors::NoPermission: The bot doesn't have the required permission to do this!>
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/api.rb:38:in `rescue in raw_request'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/api.rb:36:in `raw_request'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/api.rb:46:in `request'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/api.rb:206:in `channel'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/bot.rb:184:in `channel'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/events/channel_update.rb:18:in `initialize'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/bot.rb:973:in `new'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/bot.rb:973:in `websocket_message'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/bot.rb:815:in `block (2 levels) in websocket_connect'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `call'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `each'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `emit'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/faye-websocket-0.10.3/lib/faye/websocket/api/event_target.rb:45:in `dispatch_event'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/faye-websocket-0.10.3/lib/faye/websocket/api.rb:106:in `receive_message'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/faye-websocket-0.10.3/lib/faye/websocket/api.rb:40:in `block in initialize'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `call'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `each'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `emit'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/hybi.rb:400:in `emit_message'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/hybi.rb:383:in `emit_frame'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/hybi.rb:121:in `parse'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/websocket-driver-0.6.3/lib/websocket/driver/client.rb:63:in `parse'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/faye-websocket-0.10.3/lib/faye/websocket/api.rb:145:in `parse'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/faye-websocket-0.10.3/lib/faye/websocket/client.rb:71:in `receive_data'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /home/Avenger/.gem/ruby/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/bot.rb:811:in `websocket_connect'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/bot.rb:144:in `block (2 levels) in run_async'
[ERROR : websocket @ 2016-03-24 03:12:58.411] /cygdrive/a/devel/discord/discordrb/lib/discordrb/bot.rb:143:in `loop'
```

**Comment by avengerx** [comment]
This output came from the script I connect both on web client (chrome) and the script. I was completely afk by the time that happened.

**Comment by meew0** [comment]
This particular error occurs because discordrb tries to resolve a channel in which somebody started typing that is invisible to the bot, but as of recently Discord doesn't allow getting data of such channels over the REST API - it returns a 403 status instead. This has been fixed in v2 and probably won't be backported to master because it's not a huge problem - it just spams the console (if you don't want this, set the log mode to `:silent`)
